"""

Revision ID: c41957637310
Revises:
Create Date: 2024-12-30 15:03:25.086784

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c41957637310"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_topic",
        sa.Column("name", sa.String(length=100), nullable=False, comment="Тема вопроса"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_question_topic")),
    )
    op.create_index(op.f("ix_question_topic_uuid"), "question_topic", ["uuid"], unique=True)
    op.create_table(
        "question_type",
        sa.Column("name", sa.String(length=50), nullable=False, comment="Название типа вопроса"),
        sa.Column("params", sa.JSON(), nullable=False, comment="Параметры типа вопроса"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_question_type")),
    )
    op.create_index(op.f("ix_question_type_uuid"), "question_type", ["uuid"], unique=True)
    op.create_table(
        "quiz",
        sa.Column("name", sa.String(length=200), nullable=False, comment="Название теста"),
        sa.Column("parent_id", sa.Uuid(), nullable=True, comment="Родительский тест"),
        sa.Column("active", sa.Boolean(), nullable=False, comment="Признак активности теста"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.ForeignKeyConstraint(["parent_id"], ["quiz.uuid"], name=op.f("fk_quiz_parent_id_quiz")),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_quiz")),
    )
    op.create_index(op.f("ix_quiz_active"), "quiz", ["active"], unique=False)
    op.create_index(op.f("ix_quiz_name"), "quiz", ["name"], unique=True)
    op.create_index(op.f("ix_quiz_uuid"), "quiz", ["uuid"], unique=True)
    op.create_table(
        "user",
        sa.Column("tg_user_id", sa.Integer(), nullable=False, comment="ID пользователя в TG"),
        sa.Column("tg_username", sa.String(length=500), nullable=False, comment="Username в TG"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_tg_user_id"), "user", ["tg_user_id"], unique=True)
    op.create_index(op.f("ix_user_tg_username"), "user", ["tg_username"], unique=True)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    op.create_table(
        "question",
        sa.Column("text", sa.Text(), nullable=False, comment="Текст вопроса"),
        sa.Column("quiz_id", sa.Uuid(), nullable=False, comment="Тест"),
        sa.Column("type_id", sa.Uuid(), nullable=False, comment="Тип вопроса"),
        sa.Column("topic_id", sa.Uuid(), nullable=False, comment="Тема вопроса"),
        sa.Column("order", sa.Integer(), nullable=False, comment="Порядок вопроса"),
        sa.Column("active", sa.Boolean(), nullable=False, comment="Признак активности вопроса"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.uuid"], name=op.f("fk_question_quiz_id_quiz")),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["question_topic.uuid"], name=op.f("fk_question_topic_id_question_topic")
        ),
        sa.ForeignKeyConstraint(["type_id"], ["question_type.uuid"], name=op.f("fk_question_type_id_question_type")),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_question")),
        sa.UniqueConstraint("text", "quiz_id", name="uq_question"),
    )
    op.create_index(op.f("ix_question_active"), "question", ["active"], unique=False)
    op.create_index(op.f("ix_question_order"), "question", ["order"], unique=False)
    op.create_index(op.f("ix_question_quiz_id"), "question", ["quiz_id"], unique=False)
    op.create_index(op.f("ix_question_topic_id"), "question", ["topic_id"], unique=False)
    op.create_index(op.f("ix_question_type_id"), "question", ["type_id"], unique=False)
    op.create_index(op.f("ix_question_uuid"), "question", ["uuid"], unique=True)
    op.create_table(
        "quiz_attempt",
        sa.Column("quiz_id", sa.Uuid(), nullable=True, comment="Тест"),
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="Пользователь"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.ForeignKeyConstraint(["quiz_id"], ["quiz.uuid"], name=op.f("fk_quiz_attempt_quiz_id_quiz")),
        sa.ForeignKeyConstraint(["user_id"], ["user.uuid"], name=op.f("fk_quiz_attempt_user_id_user")),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_quiz_attempt")),
    )
    op.create_index(op.f("ix_quiz_attempt_quiz_id"), "quiz_attempt", ["quiz_id"], unique=False)
    op.create_index(op.f("ix_quiz_attempt_user_id"), "quiz_attempt", ["user_id"], unique=False)
    op.create_index(op.f("ix_quiz_attempt_uuid"), "quiz_attempt", ["uuid"], unique=True)
    op.create_table(
        "question_answer",
        sa.Column("attempt_id", sa.Uuid(), nullable=False, comment="Попытка"),
        sa.Column("question_id", sa.Uuid(), nullable=False, comment="Вопрос"),
        sa.Column("options", sa.JSON(), nullable=False, comment="Параметры ответа"),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Создано"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Обновлено"),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["quiz_attempt.uuid"], name=op.f("fk_question_answer_attempt_id_quiz_attempt")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.uuid"], name=op.f("fk_question_answer_question_id_question")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_question_answer")),
        sa.UniqueConstraint("attempt_id", "question_id", name="uq_question_answer"),
    )
    op.create_index(op.f("ix_question_answer_attempt_id"), "question_answer", ["attempt_id"], unique=False)
    op.create_index(op.f("ix_question_answer_question_id"), "question_answer", ["question_id"], unique=False)
    op.create_index(op.f("ix_question_answer_uuid"), "question_answer", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_question_answer_uuid"), table_name="question_answer")
    op.drop_index(op.f("ix_question_answer_question_id"), table_name="question_answer")
    op.drop_index(op.f("ix_question_answer_attempt_id"), table_name="question_answer")
    op.drop_table("question_answer")
    op.drop_index(op.f("ix_quiz_attempt_uuid"), table_name="quiz_attempt")
    op.drop_index(op.f("ix_quiz_attempt_user_id"), table_name="quiz_attempt")
    op.drop_index(op.f("ix_quiz_attempt_quiz_id"), table_name="quiz_attempt")
    op.drop_table("quiz_attempt")
    op.drop_index(op.f("ix_question_uuid"), table_name="question")
    op.drop_index(op.f("ix_question_type_id"), table_name="question")
    op.drop_index(op.f("ix_question_topic_id"), table_name="question")
    op.drop_index(op.f("ix_question_quiz_id"), table_name="question")
    op.drop_index(op.f("ix_question_order"), table_name="question")
    op.drop_index(op.f("ix_question_active"), table_name="question")
    op.drop_table("question")
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.drop_index(op.f("ix_user_tg_username"), table_name="user")
    op.drop_index(op.f("ix_user_tg_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_quiz_uuid"), table_name="quiz")
    op.drop_index(op.f("ix_quiz_name"), table_name="quiz")
    op.drop_index(op.f("ix_quiz_active"), table_name="quiz")
    op.drop_table("quiz")
    op.drop_index(op.f("ix_question_type_uuid"), table_name="question_type")
    op.drop_table("question_type")
    op.drop_index(op.f("ix_question_topic_uuid"), table_name="question_topic")
    op.drop_table("question_topic")
    # ### end Alembic commands ###
