"""edit question type name length

Revision ID: 7284de2a8669
Revises: c41957637310
Create Date: 2025-01-05 17:47:50.245724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7284de2a8669'
down_revision: Union[str, None] = 'c41957637310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_type', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_comment='Название типа вопроса',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_type', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_comment='Название типа вопроса',
               existing_nullable=False)
    # ### end Alembic commands ###
