"""Add quiz type model

Revision ID: 3aa9eb766534
Revises: d686ecff7a01
Create Date: 2025-01-09 01:02:10.399242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa9eb766534'
down_revision: Union[str, None] = 'd686ecff7a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_type',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название типа теста'),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Создано'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Обновлено'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_quiz_type')),
    sa.UniqueConstraint('name', name=op.f('uq_quiz_type_name'))
    )
    op.create_index(op.f('ix_quiz_type_uuid'), 'quiz_type', ['uuid'], unique=True)
    op.add_column('quiz', sa.Column('type_id', sa.Uuid(), nullable=True, comment='Тип теста'))
    op.create_unique_constraint(op.f('uq_quiz_type_id'), 'quiz', ['type_id'])
    op.create_foreign_key(op.f('fk_quiz_type_id_quiz_type'), 'quiz', 'quiz_type', ['type_id'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_quiz_type_id_quiz_type'), 'quiz', type_='foreignkey')
    op.drop_constraint(op.f('uq_quiz_type_id'), 'quiz', type_='unique')
    op.drop_column('quiz', 'type_id')
    op.drop_index(op.f('ix_quiz_type_uuid'), table_name='quiz_type')
    op.drop_table('quiz_type')
    # ### end Alembic commands ###
