[project]
name = "Personality_test"
version = "0.1.0"
description = "Personality test"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.20.0",
    "alembic>=1.14.0",
    "click>=8.1.8",
    "fastapi[standard]>=0.115.6",
    "loguru>=0.7.3",
    "polyfactory>=2.18.1",
    "pydantic-settings>=2.7.0",
    "sqlalchemy>=2.0.36",
    "uvloop>=0.21.0",
]
